import React, { useRef, useState } from 'react';
import { buyers, founder, followups, postBody } from './data';
import './scan-walkthrough.css';

const Arrow = () => <span aria-hidden="true">↗</span>;

function PostPreview({ opening, compact = false }: { opening: string; compact?: boolean }) {
  return <article className={`sw-post ${compact ? 'sw-post-compact' : ''}`} data-mockup="linkedin">
    <div className="sw-post-person"><img src={founder.avatar} alt="" width="44" height="44" /><div><strong>{founder.name}</strong><span>Customer research at CueVu</span></div><span className="sw-draft">Draft</span></div>
    <p className="sw-post-opening">{opening}</p>
    <p>{postBody[0]}</p>
    {!compact && <p>{postBody[1]}</p>}
    {compact && <div className="sw-document" aria-label="Sample document cover"><span>CueVu / Research brief</span><h3>Why did your<br />customer switch?</h3><p>A one-page brief for your next<br />customer research project.</p><div className="sw-document-bottom"><span>Category → Moment → Decision</span><span aria-hidden="true">↗</span></div></div>}
    {!compact && <p>I’ve put together a one-page research brief. Message me for a copy.</p>}
    <div className="sw-post-footer">Proposed post and download. Not published.</div>
  </article>;
}

export default function ScanWalkthroughPreview() {
  const [buyerId, setBuyerId] = useState(buyers[0].id);
  const [heroView, setHeroView] = useState('post');
  const [lane, setLane] = useState('new');
  const [category, setCategory] = useState('');
  const [decision, setDecision] = useState('Campaign messaging');
  const [downloaded, setDownloaded] = useState(false);
  const briefDialog = useRef<HTMLDialogElement>(null);
  const selected = buyers.find(b => b.id === buyerId)!;
  const downloadBrief = () => {
    const content = `CueVu | Switching-story research brief\n\nDraft sample prepared for Andrew Hayes\n\nProduct category: ${category.trim() || 'To define'}\nDecision to support: ${decision}\n\n1. Who should we hear from?\nPeople who recently changed brands in this category. Define the recency window and eligibility before recruitment.\n\n2. What happened at the switching moment?\nAsk: What were you feeling when you decided to change brands?\nRecord their exact words and the surrounding context.\n\n3. How will we use the findings?\nConnect the language to the decision above. Keep a link to the original response.\n\n4. What needs checking before publication?\nConsent to use the response, factual context, and whether the claim represents the sample.\n\nThis is a proposed brief template. No consumer responses or research findings are included.\n`;
    const url = URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' }));
    const a = document.createElement('a'); a.href = url; a.download = 'cuevu-research-brief.txt'; a.click();
    setTimeout(() => URL.revokeObjectURL(url), 1000); setDownloaded(true);
  };
  return <div className="sw-root">
    <header className="sw-header"><a className="sw-wordmark" href="#top" aria-label="InboundOnSteroids">INBOUND<b>ON</b>STEROIDS</a><span className="sw-preview-label">Design preview for Andrew</span><a className="sw-header-link" href="#scope">What we’d run <Arrow /></a></header>
    <main id="top">
      <section className="sw-hero sw-wrap" aria-labelledby="sw-title">
        <div className="sw-hero-copy"><p className="sw-eyebrow">Prepared for Andrew Hayes / CueVu</p><h1 id="sw-title">Your research.<br />Your next<br /><span className="sw-mark">conversation.</span></h1><p className="sw-lede">Andrew, we’d turn CueVu’s customer research into LinkedIn content, useful downloads and outreach to the people who buy insight.</p><a className="sw-button" href="#buyers">See who we’d reach <Arrow /></a><p className="sw-hero-note">Explore a proposed post, download and message.<br />Built around your public offer.</p></div>
        <div className="sw-hero-demo"><h2 className="sw-visually-hidden">Proposed content for CueVu</h2><div className="sw-demo-toolbar" role="group" aria-label="Explore the example"><button aria-pressed={heroView === 'post'} onClick={() => setHeroView('post')}>The post</button><button aria-pressed={heroView === 'download'} onClick={() => setHeroView('download')}>The download</button><button aria-pressed={heroView === 'message'} onClick={() => setHeroView('message')}>The message</button></div>
          <div className="sw-demo-stage" key={heroView}>
            {heroView === 'post' && <PostPreview opening={buyers[0].post} compact />}
            {heroView === 'download' && <div className="sw-hero-download"><span className="sw-eyebrow">Proposed CueVu download</span><h3>Plan the research<br />before the brief.</h3><p>A short worksheet for a marketing team deciding what to ask customers who changed brands.</p><dl><div><dt>Start with</dt><dd>The product category</dd></div><div><dt>Ask about</dt><dd>The switching moment</dd></div><div><dt>Use it for</dt><dd>A real campaign decision</dd></div></dl><button className="sw-text-button" onClick={() => briefDialog.current?.showModal()}>Open the sample brief <Arrow /></button></div>}
            {heroView === 'message' && <div className="sw-hero-message"><p className="sw-eyebrow">Proposed first message</p><h3>For a brand<br />marketing lead.</h3><p>{buyers[0].message}</p><div className="sw-demo-footnote">We’d verify the person’s role and company fit before reaching out.</div></div>}
          </div>
          <p className="sw-demo-caption">One example of the work we’d run under your name.</p>
        </div>
      </section>

      <nav className="sw-section-nav sw-wrap" aria-label="Preview sections"><a href="#buyers"><span>01</span> Your buyers</a><a href="#inbound"><span>02</span> Content & inbound</a><a href="#outreach"><span>03</span> Outreach</a><a href="#scope"><span>04</span> What we run</a></nav>

      <section id="buyers" className="sw-buyers sw-wrap" aria-labelledby="buyers-title"><div className="sw-section-heading"><p className="sw-eyebrow">01 / The people we’d reach</p><h2 id="buyers-title">Who buys<br />what you know?</h2><p>CueVu sells customer insight. We’d start with the people commissioning research and deciding how to use it.</p><p className="sw-small">Proposed buyer profiles, based on your public offer. Select one to see the angle.</p></div>
        <div className="sw-buyer-workspace"><div className="sw-buyer-list" role="group" aria-label="Proposed buyer profiles">{buyers.map((buyer, i) => <button key={buyer.id} aria-pressed={buyer.id === buyerId} onClick={() => setBuyerId(buyer.id)}><span className="sw-buyer-index">0{i + 1}</span><span><strong>{buyer.name}</strong><small>{buyer.company}</small></span><span aria-hidden="true">{buyer.id === buyerId ? '↙' : '↗'}</span></button>)}</div><div className="sw-buyer-detail" aria-live="polite"><p className="sw-eyebrow">Why this could fit</p><p>{selected.reason}</p><div className="sw-buyer-columns"><div><span className="sw-small-label">A reason to reach out</span><p>{selected.signal}</p></div><div><span className="sw-small-label">The content angle</span><p>{selected.angle}</p></div></div></div><a className="sw-text-link" href="#outreach">See the message for this buyer <Arrow /></a></div>
      </section>

      <section id="inbound" className="sw-inbound" aria-labelledby="inbound-title"><div className="sw-wrap"><div className="sw-inbound-heading"><div><p className="sw-eyebrow">02 / Content & inbound</p><h2 id="inbound-title">Give the right reader<br />something to use.</h2></div><p>We’d write the post, build the download and follow up with people who request it. Each piece leads naturally to a conversation about their research.</p></div>
        <div className="sw-inbound-grid"><div className="sw-content-example"><span className="sw-small-label">A post for {selected.name.toLowerCase()}</span><PostPreview opening={selected.post} /><details className="sw-details"><summary>Read the complete post <span aria-hidden="true">+</span></summary><div className="sw-expanded-post"><p>{selected.post}</p>{postBody.map(p => <p key={p}>{p}</p>)}<a href={founder.source} target="_blank" rel="noreferrer">Based on your public research method <Arrow /></a></div></details></div>
        <div className="sw-download-example"><div className="sw-brief-preview"><div className="sw-brief-masthead"><strong>CueVu</strong><span>Sample worksheet</span></div><h3>The switching-story<br />research brief.</h3><p>Define the question before you recruit.</p><div className="sw-worksheet-row"><span>Product category</span><div>Which market are you studying?</div></div><div className="sw-worksheet-row"><span>The switching moment</span><div>What happened just before they changed brands?</div></div><div className="sw-worksheet-row"><span>The decision</span><div>What will your team do with the answer?</div></div><button className="sw-button" onClick={() => briefDialog.current?.showModal()}>Try the sample brief <Arrow /></button></div><div className="sw-next-step"><span className="sw-small-label">After someone asks for it</span><h3>Keep the conversation going.</h3><p>The follow-up asks about the project they’re working on. You can see the proposed emails below.</p>{followups.map(f => <details className="sw-details" key={f.day}><summary><span><small>{f.day}</small>{f.subject}</span><span aria-hidden="true">+</span></summary><p>{f.body}</p></details>)}</div></div></div>
      </div></section>

      <section id="outreach" className="sw-outreach sw-wrap" aria-labelledby="outreach-title"><div className="sw-section-heading"><p className="sw-eyebrow">03 / Outreach</p><h2 id="outreach-title">A clear reason<br />to get in touch.</h2><p>We’d research potential buyers and write the first message around what could be useful to them.</p><p className="sw-small">Warm conversations and new prospects need different openings. Both examples here are drafts.</p></div><div className="sw-message-workspace"><div className="sw-demo-toolbar" role="group" aria-label="Outreach example"><button aria-pressed={lane === 'new'} onClick={() => setLane('new')}>A new prospect</button><button aria-pressed={lane === 'warm'} onClick={() => setLane('warm')}>From your comments</button></div><div className="sw-message-card" data-mockup="message"><div className="sw-message-recipient"><span className="sw-avatar-initials" aria-hidden="true">{lane === 'new' ? 'To' : 'LA'}</span><div><strong>{lane === 'new' ? selected.name : 'Lorenzo Asnaghi'}</strong><span>{lane === 'new' ? 'Proposed buyer profile' : 'COO at growthcab.com'}</span></div></div><div className="sw-message-body" aria-live="polite"><p>{lane === 'new' ? selected.message : 'Hi Lorenzo, thanks for joining the conversation on the Marcus and Becky story. Do you use customer stories in your work at GrowthCab? I put together a short research brief for collecting them, happy to share it.'}</p></div><div className="sw-message-status">Draft for Andrew / not sent</div></div><p className="sw-small sw-message-note">{lane === 'new' ? 'This uses the buyer profile you selected above. A real outreach list would include named people, evidence of fit and a source for each relevant signal.' : 'Lorenzo appears in the comments recorded by the August 13 scan. His current role, buyer fit and any existing conversation still need checking.'}</p>{lane === 'new' && <a href="#buyers" className="sw-text-link">Change the buyer profile ↑</a>}</div></section>

      <section id="scope" className="sw-scope sw-wrap" aria-labelledby="scope-title"><div className="sw-scope-box"><div><p className="sw-eyebrow">What we’d run for CueVu</p><h2 id="scope-title">We run your LinkedIn<br />from post to conversation.</h2><p>We’d handle the content and follow-up, with the audience, email list and content staying yours.</p></div><dl><div><dt>Publishing</dt><dd>Posts grounded in your material and written for your buyers.</dd></div><div><dt>Inbound</dt><dd>A useful download, a page to request it, and email follow-up.</dd></div><div><dt>Outreach</dt><dd>Buyer research, relevant messages and ongoing conversations.</dd></div></dl></div><div className="sw-final"><div><h3>Talk through the fit for CueVu.</h3><p>We’ll look at your current setup and choose where to begin.</p></div><a className="sw-button" href="https://inboundonsteroids.com/start" target="_blank" rel="noreferrer">Talk through the setup <Arrow /></a></div></section>
    </main>
    <footer className="sw-footer sw-wrap"><span>Prepared for Andrew Hayes by Iván Manfredi.</span><span>Concept preview / samples are unpublished</span><a href={founder.source} target="_blank" rel="noreferrer">Source: your public LinkedIn <Arrow /></a></footer>
    <dialog className="sw-dialog" ref={briefDialog} aria-labelledby="brief-title" onClick={event => { if (event.target === event.currentTarget) briefDialog.current?.close(); }}><div className="sw-dialog-inner"><div className="sw-dialog-top"><span>CueVu / Sample research brief</span><button aria-label="Close sample brief" onClick={() => briefDialog.current?.close()}>×</button></div><h2 id="brief-title">Start with a<br />real decision.</h2><p>Try the worksheet. Download your filled-in brief as a text file.</p><form onSubmit={event => { event.preventDefault(); downloadBrief(); }}><label htmlFor="sw-category">What product category are you researching?</label><input id="sw-category" value={category} onChange={event => { setCategory(event.target.value); setDownloaded(false); }} placeholder="e.g. pet food" maxLength={120} /><label htmlFor="sw-decision">What will the research help you decide?</label><select id="sw-decision" value={decision} onChange={event => { setDecision(event.target.value); setDownloaded(false); }}><option>Campaign messaging</option><option>A creative brief</option><option>Product positioning</option><option>A customer experience decision</option></select><div className="sw-brief-question"><span className="sw-small-label">A starting question</span><p>What were you feeling when you decided to change brands?</p></div><button className="sw-button" type="submit">Download the brief ↓</button><p className="sw-small" role="status">{downloaded ? 'Your brief has been downloaded.' : 'Preview only. No email required. Nothing is sent to CueVu.'}</p></form></div></dialog>
  </div>;
}
