-- RLS closure (goal-run dashboard-interiors-auth-2026-07-19). Applied live 2026-07-19 in waves
-- (2a adds -> wave0 named leakers -> wave1 enables -> wave2 policy removals -> wave2b views+RPCs).
-- Rollback files: goal-runs/dashboard-interiors-auth-2026-07-19/02-rls-sql/*-rollback.sql

-- ===== phase 2a: authenticated/service adds =====
create policy authenticated_all on public.outreach_prospects for all to authenticated using (true) with check (true);
create policy authenticated_all on public.outreach_messages for all to authenticated using (true) with check (true);
create policy authenticated_all on public.outreach_campaigns for all to authenticated using (true) with check (true);
create policy authenticated_all on public.video_ideas for all to authenticated using (true) with check (true);
create policy authenticated_all on public.aios_capabilities for all to authenticated using (true) with check (true);
create policy authenticated_all on public.audience_audits for all to authenticated using (true) with check (true);
create policy authenticated_all on public.auto_research_iterations for all to authenticated using (true) with check (true);
create policy authenticated_all on public.auto_research_sessions for all to authenticated using (true) with check (true);
create policy authenticated_all on public.calendar_events for all to authenticated using (true) with check (true);
create policy authenticated_all on public.call_reports for all to authenticated using (true) with check (true);
create policy authenticated_all on public.claude_memory for all to authenticated using (true) with check (true);
create policy authenticated_all on public.claude_memory_backlinks for all to authenticated using (true) with check (true);
create policy authenticated_all on public.claude_memory_relations for all to authenticated using (true) with check (true);
create policy authenticated_all on public.client_workflow_errors for all to authenticated using (true) with check (true);
create policy authenticated_all on public.competitor_patterns for all to authenticated using (true) with check (true);
create policy authenticated_all on public.competitor_posts for all to authenticated using (true) with check (true);
create policy authenticated_all on public.contacts for all to authenticated using (true) with check (true);
create policy authenticated_all on public.contact_links for all to authenticated using (true) with check (true);
create policy authenticated_all on public.content_insights for all to authenticated using (true) with check (true);
create policy authenticated_all on public.custom_tools for all to authenticated using (true) with check (true);
create policy authenticated_all on public.dashboard_stack_status for all to authenticated using (true) with check (true);
create policy authenticated_all on public.dashboard_tasks for all to authenticated using (true) with check (true);
create policy authenticated_all on public.dashboard_workflow_stats for all to authenticated using (true) with check (true);
create policy authenticated_all on public.email_threads for all to authenticated using (true) with check (true);
create policy authenticated_all on public.generated_posts for all to authenticated using (true) with check (true);
create policy authenticated_all on public.health_inventory for all to authenticated using (true) with check (true);
create policy authenticated_all on public.health_medication_logs for all to authenticated using (true) with check (true);
create policy authenticated_all on public.health_medications for all to authenticated using (true) with check (true);
create policy authenticated_all on public.health_training_logs for all to authenticated using (true) with check (true);
create policy authenticated_all on public.health_training_schedule for all to authenticated using (true) with check (true);
create policy authenticated_all on public.health_weight_logs for all to authenticated using (true) with check (true);
create policy authenticated_all on public.interview_clips for all to authenticated using (true) with check (true);
create policy authenticated_all on public.lead_magnets for all to authenticated using (true) with check (true);
create policy authenticated_all on public.leads for all to authenticated using (true) with check (true);
create policy authenticated_all on public.linkedin_follower_history for all to authenticated using (true) with check (true);
create policy authenticated_all on public.listener_state for all to authenticated using (true) with check (true);
create policy authenticated_all on public.lm_events for all to authenticated using (true) with check (true);
create policy authenticated_all on public.lm_idea_candidates for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_chat_messages for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_clients for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_daily_summaries for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_expenses for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_health_metrics for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_meals for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_portfolio_snapshots for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_proactive_alerts for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_reminders for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_tool_invocations for all to authenticated using (true) with check (true);
create policy authenticated_all on public.n8nclaw_tool_usage for all to authenticated using (true) with check (true);
create policy authenticated_all on public.newsletter_issues for all to authenticated using (true) with check (true);
create policy authenticated_all on public.notification_muted_categories for all to authenticated using (true) with check (true);
create policy authenticated_all on public.notification_seen for all to authenticated using (true) with check (true);
create policy authenticated_all on public.nurture_emails for all to authenticated using (true) with check (true);
create policy authenticated_all on public.nurture_events for all to authenticated using (true) with check (true);
create policy authenticated_all on public.nurture_queue for all to authenticated using (true) with check (true);
create policy authenticated_all on public.nurture_sequences for all to authenticated using (true) with check (true);
create policy authenticated_all on public.nurture_subscribers for all to authenticated using (true) with check (true);
create policy authenticated_all on public.outreach_engagement_log for all to authenticated using (true) with check (true);
create policy authenticated_all on public.outreach_link_clicks for all to authenticated using (true) with check (true);
create policy authenticated_all on public.pageviews for all to authenticated using (true) with check (true);
create policy authenticated_all on public.push_subscriptions for all to authenticated using (true) with check (true);
create policy authenticated_all on public.room_buyers for all to authenticated using (true) with check (true);
create policy authenticated_all on public.sales_objections for all to authenticated using (true) with check (true);
create policy authenticated_all on public.sales_scripts for all to authenticated using (true) with check (true);
create policy authenticated_all on public.scheduled_checks for all to authenticated using (true) with check (true);
create policy authenticated_all on public.scheduled_job_registry for all to authenticated using (true) with check (true);
create policy authenticated_all on public.scheduled_run_log for all to authenticated using (true) with check (true);
create policy authenticated_all on public.scheduled_posts for all to authenticated using (true) with check (true);
create policy authenticated_all on public.signal_clusters for all to authenticated using (true) with check (true);
create policy authenticated_all on public.skill_drafts for all to authenticated using (true) with check (true);
create policy authenticated_all on public.slack_available_channels for all to authenticated using (true) with check (true);
create policy authenticated_all on public.slack_notification_channels for all to authenticated using (true) with check (true);
create policy authenticated_all on public.transcript_chunks for all to authenticated using (true) with check (true);
create policy authenticated_all on public.transcripts for all to authenticated using (true) with check (true);
create policy authenticated_all on public.upwork_jobs for all to authenticated using (true) with check (true);
create policy authenticated_all on public.upwork_proposals for all to authenticated using (true) with check (true);
create policy authenticated_all on public.workflow_cache for all to authenticated using (true) with check (true);
create policy authenticated_all on public.workflow_execution_logs for all to authenticated using (true) with check (true);
create policy authenticated_all on public.recordings for all to authenticated using (true) with check (true);
create policy service_role_only on public.recordings for all to service_role using (true) with check (true);
create policy authenticated_all on public.recording_segments for all to authenticated using (true) with check (true);
create policy service_role_only on public.recording_segments for all to service_role using (true) with check (true);
create policy authenticated_all on public.recording_transcripts for all to authenticated using (true) with check (true);
create policy service_role_only on public.recording_transcripts for all to service_role using (true) with check (true);
create policy authenticated_all on public.recording_transcript_words for all to authenticated using (true) with check (true);
create policy service_role_only on public.recording_transcript_words for all to service_role using (true) with check (true);
create policy authenticated_all on public.upwork_conversations for all to authenticated using (true) with check (true);
create policy service_role_only on public.upwork_conversations for all to service_role using (true) with check (true);
create policy authenticated_all on public.upwork_safety_log for all to authenticated using (true) with check (true);
create policy service_role_only on public.upwork_safety_log for all to service_role using (true) with check (true);
create policy authenticated_all on public.portfolio_projects for all to authenticated using (true) with check (true);
create policy service_role_only on public.portfolio_projects for all to service_role using (true) with check (true);
create policy authenticated_all on public.client_monitored_workflows for all to authenticated using (true) with check (true);
create policy service_role_only on public.client_monitored_workflows for all to service_role using (true) with check (true);
create policy authenticated_all on public.integration_config for all to authenticated using (true) with check (true);
create policy authenticated_all on public.hypertarget_corpus for all to authenticated using (true) with check (true);

-- ===== wave 0: named leakers =====
drop policy "anon_delete_prospects" on public.outreach_prospects;
drop policy "anon_read_prospects" on public.outreach_prospects;
drop policy "anon_update_prospects" on public.outreach_prospects;
drop policy "anon_write_prospects" on public.outreach_prospects;
drop policy "anon_read_messages" on public.outreach_messages;
drop policy "anon_update_messages" on public.outreach_messages;
drop policy "anon_write_messages" on public.outreach_messages;
drop policy "anon_delete_campaigns" on public.outreach_campaigns;
drop policy "anon_read_campaigns" on public.outreach_campaigns;
drop policy "anon_update_campaigns" on public.outreach_campaigns;
drop policy "anon_write_campaigns" on public.outreach_campaigns;
alter table public.carousel_drafts enable row level security;
create policy authenticated_all on public.carousel_drafts for all to authenticated using (true) with check (true);
create policy service_role_all on public.carousel_drafts for all to service_role using (true) with check (true);
drop policy if exists anon_own_rows on public.carousel_drafts; -- latent policy found at apply time

-- ===== wave 1: enable RLS everywhere =====
alter table public.assessment_intakes enable row level security;
create policy authenticated_all on public.assessment_intakes for all to authenticated using (true) with check (true);
create policy service_role_all on public.assessment_intakes for all to service_role using (true) with check (true);
alter table public.carousel_assets enable row level security;
create policy authenticated_all on public.carousel_assets for all to authenticated using (true) with check (true);
create policy service_role_all on public.carousel_assets for all to service_role using (true) with check (true);
alter table public.carousel_styles enable row level security;
create policy authenticated_all on public.carousel_styles for all to authenticated using (true) with check (true);
create policy service_role_all on public.carousel_styles for all to service_role using (true) with check (true);
alter table public.claude_session_index enable row level security;
create policy authenticated_all on public.claude_session_index for all to authenticated using (true) with check (true);
create policy service_role_all on public.claude_session_index for all to service_role using (true) with check (true);
alter table public.claude_usage_sessions enable row level security;
create policy authenticated_all on public.claude_usage_sessions for all to authenticated using (true) with check (true);
create policy service_role_all on public.claude_usage_sessions for all to service_role using (true) with check (true);
alter table public.client_content_blocks enable row level security;
create policy authenticated_all on public.client_content_blocks for all to authenticated using (true) with check (true);
create policy service_role_all on public.client_content_blocks for all to service_role using (true) with check (true);
alter table public.clip_render_log enable row level security;
create policy authenticated_all on public.clip_render_log for all to authenticated using (true) with check (true);
create policy service_role_all on public.clip_render_log for all to service_role using (true) with check (true);
alter table public.cohort_posts enable row level security;
create policy authenticated_all on public.cohort_posts for all to authenticated using (true) with check (true);
create policy service_role_all on public.cohort_posts for all to service_role using (true) with check (true);
alter table public.comment_feed enable row level security;
create policy authenticated_all on public.comment_feed for all to authenticated using (true) with check (true);
create policy service_role_all on public.comment_feed for all to service_role using (true) with check (true);
alter table public.commenting_log enable row level security;
create policy authenticated_all on public.commenting_log for all to authenticated using (true) with check (true);
create policy service_role_all on public.commenting_log for all to service_role using (true) with check (true);
alter table public.commenting_targets enable row level security;
create policy authenticated_all on public.commenting_targets for all to authenticated using (true) with check (true);
create policy service_role_all on public.commenting_targets for all to service_role using (true) with check (true);
alter table public.content_archetypes enable row level security;
create policy authenticated_all on public.content_archetypes for all to authenticated using (true) with check (true);
create policy service_role_all on public.content_archetypes for all to service_role using (true) with check (true);
alter table public.content_audit_reports enable row level security;
create policy authenticated_all on public.content_audit_reports for all to authenticated using (true) with check (true);
create policy service_role_all on public.content_audit_reports for all to service_role using (true) with check (true);
alter table public.content_industry_map enable row level security;
create policy authenticated_all on public.content_industry_map for all to authenticated using (true) with check (true);
create policy service_role_all on public.content_industry_map for all to service_role using (true) with check (true);
alter table public.content_prompt_versions enable row level security;
create policy authenticated_all on public.content_prompt_versions for all to authenticated using (true) with check (true);
create policy service_role_all on public.content_prompt_versions for all to service_role using (true) with check (true);
alter table public.content_prompts enable row level security;
create policy authenticated_all on public.content_prompts for all to authenticated using (true) with check (true);
create policy service_role_all on public.content_prompts for all to service_role using (true) with check (true);
alter table public.content_quality_daily enable row level security;
create policy authenticated_all on public.content_quality_daily for all to authenticated using (true) with check (true);
create policy service_role_all on public.content_quality_daily for all to service_role using (true) with check (true);
alter table public.crowd_patterns enable row level security;
create policy authenticated_all on public.crowd_patterns for all to authenticated using (true) with check (true);
create policy service_role_all on public.crowd_patterns for all to service_role using (true) with check (true);
alter table public.domain_screens enable row level security;
create policy authenticated_all on public.domain_screens for all to authenticated using (true) with check (true);
create policy service_role_all on public.domain_screens for all to service_role using (true) with check (true);
alter table public.edge_rate_counter enable row level security;
create policy authenticated_all on public.edge_rate_counter for all to authenticated using (true) with check (true);
create policy service_role_all on public.edge_rate_counter for all to service_role using (true) with check (true);
alter table public.followup_drafts enable row level security;
create policy authenticated_all on public.followup_drafts for all to authenticated using (true) with check (true);
create policy service_role_all on public.followup_drafts for all to service_role using (true) with check (true);
alter table public.founder_notes enable row level security;
create policy authenticated_all on public.founder_notes for all to authenticated using (true) with check (true);
create policy service_role_all on public.founder_notes for all to service_role using (true) with check (true);
alter table public.fractional_sessions enable row level security;
create policy authenticated_all on public.fractional_sessions for all to authenticated using (true) with check (true);
create policy service_role_all on public.fractional_sessions for all to service_role using (true) with check (true);
alter table public.free_diagnostics enable row level security;
create policy authenticated_all on public.free_diagnostics for all to authenticated using (true) with check (true);
create policy service_role_all on public.free_diagnostics for all to service_role using (true) with check (true);
alter table public.harvest_sources enable row level security;
create policy authenticated_all on public.harvest_sources for all to authenticated using (true) with check (true);
create policy service_role_all on public.harvest_sources for all to service_role using (true) with check (true);
alter table public.hiring_role_offer_map enable row level security;
create policy authenticated_all on public.hiring_role_offer_map for all to authenticated using (true) with check (true);
create policy service_role_all on public.hiring_role_offer_map for all to service_role using (true) with check (true);
alter table public.image_edit_versions enable row level security;
create policy authenticated_all on public.image_edit_versions for all to authenticated using (true) with check (true);
create policy service_role_all on public.image_edit_versions for all to service_role using (true) with check (true);
alter table public.known_models enable row level security;
create policy authenticated_all on public.known_models for all to authenticated using (true) with check (true);
create policy service_role_all on public.known_models for all to service_role using (true) with check (true);
alter table public.kyle_call_raw enable row level security;
create policy authenticated_all on public.kyle_call_raw for all to authenticated using (true) with check (true);
create policy service_role_all on public.kyle_call_raw for all to service_role using (true) with check (true);
alter table public.kyle_call_transcripts enable row level security;
create policy authenticated_all on public.kyle_call_transcripts for all to authenticated using (true) with check (true);
create policy service_role_all on public.kyle_call_transcripts for all to service_role using (true) with check (true);
alter table public.lifestyle_ideas enable row level security;
create policy authenticated_all on public.lifestyle_ideas for all to authenticated using (true) with check (true);
create policy service_role_all on public.lifestyle_ideas for all to service_role using (true) with check (true);
alter table public.lifestyle_pattern_examples enable row level security;
create policy authenticated_all on public.lifestyle_pattern_examples for all to authenticated using (true) with check (true);
create policy service_role_all on public.lifestyle_pattern_examples for all to service_role using (true) with check (true);
alter table public.linkedin_auto_comments enable row level security;
create policy authenticated_all on public.linkedin_auto_comments for all to authenticated using (true) with check (true);
create policy service_role_all on public.linkedin_auto_comments for all to service_role using (true) with check (true);
alter table public.linkedin_comment_events enable row level security;
create policy authenticated_all on public.linkedin_comment_events for all to authenticated using (true) with check (true);
create policy service_role_all on public.linkedin_comment_events for all to service_role using (true) with check (true);
alter table public.linkedin_daily_actions enable row level security;
create policy authenticated_all on public.linkedin_daily_actions for all to authenticated using (true) with check (true);
create policy service_role_all on public.linkedin_daily_actions for all to service_role using (true) with check (true);
alter table public.lm_curator_examples enable row level security;
create policy authenticated_all on public.lm_curator_examples for all to authenticated using (true) with check (true);
create policy service_role_all on public.lm_curator_examples for all to service_role using (true) with check (true);
alter table public.lm_curator_seeds enable row level security;
create policy authenticated_all on public.lm_curator_seeds for all to authenticated using (true) with check (true);
create policy service_role_all on public.lm_curator_seeds for all to service_role using (true) with check (true);
alter table public.lm_drafts_v2 enable row level security;
create policy authenticated_all on public.lm_drafts_v2 for all to authenticated using (true) with check (true);
create policy service_role_all on public.lm_drafts_v2 for all to service_role using (true) with check (true);
alter table public.lm_idea_review_decisions enable row level security;
create policy authenticated_all on public.lm_idea_review_decisions for all to authenticated using (true) with check (true);
create policy service_role_all on public.lm_idea_review_decisions for all to service_role using (true) with check (true);
alter table public.lm_prospect_enrichment enable row level security;
create policy authenticated_all on public.lm_prospect_enrichment for all to authenticated using (true) with check (true);
create policy service_role_all on public.lm_prospect_enrichment for all to service_role using (true) with check (true);
alter table public.lm_walkthrough_quota enable row level security;
create policy authenticated_all on public.lm_walkthrough_quota for all to authenticated using (true) with check (true);
create policy service_role_all on public.lm_walkthrough_quota for all to service_role using (true) with check (true);
alter table public.newsletter_ideas enable row level security;
create policy authenticated_all on public.newsletter_ideas for all to authenticated using (true) with check (true);
create policy service_role_all on public.newsletter_ideas for all to service_role using (true) with check (true);
alter table public.newsletter_topic_queue enable row level security;
create policy authenticated_all on public.newsletter_topic_queue for all to authenticated using (true) with check (true);
create policy service_role_all on public.newsletter_topic_queue for all to service_role using (true) with check (true);
alter table public.paid_assessments enable row level security;
create policy authenticated_all on public.paid_assessments for all to authenticated using (true) with check (true);
create policy service_role_all on public.paid_assessments for all to service_role using (true) with check (true);
alter table public.prompt_version_log enable row level security;
create policy authenticated_all on public.prompt_version_log for all to authenticated using (true) with check (true);
create policy service_role_all on public.prompt_version_log for all to service_role using (true) with check (true);
alter table public.silent_failures enable row level security;
create policy authenticated_all on public.silent_failures for all to authenticated using (true) with check (true);
create policy service_role_all on public.silent_failures for all to service_role using (true) with check (true);
alter table public.slack_workspaces enable row level security;
create policy authenticated_all on public.slack_workspaces for all to authenticated using (true) with check (true);
create policy service_role_all on public.slack_workspaces for all to service_role using (true) with check (true);
alter table public.social_proof enable row level security;
create policy authenticated_all on public.social_proof for all to authenticated using (true) with check (true);
create policy service_role_all on public.social_proof for all to service_role using (true) with check (true);
alter table public.system_settings enable row level security;
create policy authenticated_all on public.system_settings for all to authenticated using (true) with check (true);
create policy service_role_all on public.system_settings for all to service_role using (true) with check (true);
alter table public.video_shorts enable row level security;
create policy authenticated_all on public.video_shorts for all to authenticated using (true) with check (true);
create policy service_role_all on public.video_shorts for all to service_role using (true) with check (true);
alter table public.webhook_debug_log enable row level security;
create policy authenticated_all on public.webhook_debug_log for all to authenticated using (true) with check (true);
create policy service_role_all on public.webhook_debug_log for all to service_role using (true) with check (true);
alter table public.wip_branches enable row level security;
create policy authenticated_all on public.wip_branches for all to authenticated using (true) with check (true);
create policy service_role_all on public.wip_branches for all to service_role using (true) with check (true);
alter table public.blueprints enable row level security;
alter table public.video_ideas enable row level security;
create policy anon_read on public.video_ideas for select to anon using (true);
create policy service_role_all on public.video_ideas for all to service_role using (true) with check (true);

-- ===== wave 2: remove anon/public open policies =====
drop policy if exists "aios_capabilities_read" on public.aios_capabilities;
drop policy if exists "anon_read" on public.auto_research_iterations;
drop policy if exists "anon_read" on public.auto_research_sessions;
drop policy if exists "anon_update_meeting_type_calendar" on public.calendar_events;
drop policy if exists "claude_memory_anon_select" on public.claude_memory;
drop policy if exists "claude_memory_backlinks_anon_select" on public.claude_memory_backlinks;
drop policy if exists "claude_memory_relations_anon_select" on public.claude_memory_relations;
drop policy if exists "anon_select_client_errors" on public.client_workflow_errors;
drop policy if exists "anon_select" on public.competitor_patterns;
drop policy if exists "anon_select" on public.competitor_posts;
drop policy if exists "contacts_anon_delete" on public.contacts;
drop policy if exists "contacts_anon_insert" on public.contacts;
drop policy if exists "contacts_anon_read" on public.contacts;
drop policy if exists "contacts_anon_update" on public.contacts;
drop policy if exists "clinks_anon_delete" on public.contact_links;
drop policy if exists "clinks_anon_insert" on public.contact_links;
drop policy if exists "clinks_anon_read" on public.contact_links;
drop policy if exists "clinks_anon_update" on public.contact_links;
drop policy if exists "anon_select" on public.content_insights;
drop policy if exists "anon_select" on public.custom_tools;
drop policy if exists "dashboard_stack_status_read" on public.dashboard_stack_status;
drop policy if exists "Anon read access on dashboard_tasks" on public.dashboard_tasks;
drop policy if exists "Anon read access" on public.dashboard_workflow_stats;
drop policy if exists "Anon read access on dashboard_workflow_stats" on public.dashboard_workflow_stats;
drop policy if exists "anon_select" on public.dashboard_workflow_stats;
drop policy if exists "ethreads_anon_read" on public.email_threads;
drop policy if exists "ethreads_anon_update" on public.email_threads;
drop policy if exists "ethreads_anon_write" on public.email_threads;
drop policy if exists "anon_select" on public.generated_posts;
drop policy if exists "anon_select" on public.health_inventory;
drop policy if exists "anon_select" on public.health_medication_logs;
drop policy if exists "anon_select" on public.health_medications;
drop policy if exists "anon_select" on public.health_training_logs;
drop policy if exists "anon_select" on public.health_training_schedule;
drop policy if exists "anon_select" on public.health_weight_logs;
drop policy if exists "interview_clips anon delete" on public.interview_clips;
drop policy if exists "interview_clips anon insert" on public.interview_clips;
drop policy if exists "interview_clips anon read" on public.interview_clips;
drop policy if exists "interview_clips anon update" on public.interview_clips;
drop policy if exists "anon_select" on public.lead_magnets;
drop policy if exists "anon_select" on public.leads;
drop policy if exists "read_follower_history" on public.linkedin_follower_history;
drop policy if exists "anon read listener state" on public.listener_state;
drop policy if exists "anon write pending_command" on public.listener_state;
drop policy if exists "anon_select" on public.lm_events;
drop policy if exists "anon_select" on public.lm_idea_candidates;
drop policy if exists "anon_select" on public.n8nclaw_chat_messages;
drop policy if exists "anon_select" on public.n8nclaw_clients;
drop policy if exists "anon_select" on public.n8nclaw_daily_summaries;
drop policy if exists "anon_select" on public.n8nclaw_expenses;
drop policy if exists "anon_select" on public.n8nclaw_health_metrics;
drop policy if exists "anon_select" on public.n8nclaw_meals;
drop policy if exists "anon_select" on public.n8nclaw_portfolio_snapshots;
drop policy if exists "anon_select" on public.n8nclaw_proactive_alerts;
drop policy if exists "anon_select" on public.n8nclaw_reminders;
drop policy if exists "nti_anon_select" on public.n8nclaw_tool_invocations;
drop policy if exists "anon_select" on public.n8nclaw_tool_usage;
drop policy if exists "anon_select" on public.newsletter_issues;
drop policy if exists "notif_mute_rw" on public.notification_muted_categories;
drop policy if exists "notification_seen_rw" on public.notification_seen;
drop policy if exists "anon_select" on public.nurture_emails;
drop policy if exists "anon_select" on public.nurture_events;
drop policy if exists "anon_select" on public.nurture_queue;
drop policy if exists "anon_select" on public.nurture_sequences;
drop policy if exists "anon_select" on public.nurture_subscribers;
drop policy if exists "anon_read_engagement" on public.outreach_engagement_log;
drop policy if exists "anon_update_engagement" on public.outreach_engagement_log;
drop policy if exists "anon_write_engagement" on public.outreach_engagement_log;
drop policy if exists "outreach_link_clicks_anon_insert" on public.outreach_link_clicks;
drop policy if exists "pageviews_anon_select" on public.pageviews;
drop policy if exists "anon_delete_own_endpoint" on public.push_subscriptions;
drop policy if exists "anon_update_own_endpoint" on public.push_subscriptions;
drop policy if exists "anon_upsert_own_endpoint" on public.push_subscriptions;
drop policy if exists "anon_select" on public.room_buyers;
drop policy if exists "anon_full_access_sales_objections" on public.sales_objections;
drop policy if exists "anon_full_access_sales_scripts" on public.sales_scripts;
create policy anon_read_scripts on public.sales_scripts for select to anon using (true);
drop policy if exists "scheduled_checks_anon_rw" on public.scheduled_checks;
drop policy if exists "scheduled_job_registry_read" on public.scheduled_job_registry;
drop policy if exists "scheduled_run_log_read" on public.scheduled_run_log;
drop policy if exists "anon_select_scheduled_posts" on public.scheduled_posts;
drop policy if exists "anon_update_scheduled_posts" on public.scheduled_posts;
create policy anon_read_posted on public.scheduled_posts for select to anon using (status = 'posted');
drop policy if exists "signal_clusters_anon_select" on public.signal_clusters;
drop policy if exists "skill_drafts_anon_read" on public.skill_drafts;
drop policy if exists "anon_select" on public.slack_available_channels;
drop policy if exists "anon_select" on public.slack_notification_channels;
drop policy if exists "anon_select" on public.transcript_chunks;
drop policy if exists "anon_select" on public.upwork_jobs;
drop policy if exists "anon_select" on public.upwork_proposals;
drop policy if exists "anon_select" on public.workflow_cache;
drop policy if exists "Allow read for anon" on public.workflow_execution_logs;
drop policy if exists "service_role_all" on public.recordings;
drop policy if exists "service_role_all" on public.recording_segments;
drop policy if exists "service_role_all" on public.recording_transcripts;
drop policy if exists "service_role_all" on public.recording_transcript_words;
drop policy if exists "service_role_all" on public.upwork_conversations;
drop policy if exists "Service role full access" on public.upwork_safety_log;
drop policy if exists "Service role full access" on public.portfolio_projects;
drop policy if exists "Service role full access" on public.client_monitored_workflows;
drop policy if exists "non_secret_config_access" on public.integration_config;
create policy anon_read_non_secret on public.integration_config for select to anon using (is_secret = false);

-- ===== wave 2b: views + RPC hardening =====
revoke select on public.assessment_weakest_rollup from anon;
grant select on public.assessment_weakest_rollup to authenticated;
revoke select on public.claude_usage_daily from anon;
grant select on public.claude_usage_daily to authenticated;
revoke select on public.client_instances_safe from anon;
grant select on public.client_instances_safe to authenticated;
revoke select on public.client_monitored_workflows_view from anon;
grant select on public.client_monitored_workflows_view to authenticated;
revoke select on public.content_lint_detector_stats from anon;
grant select on public.content_lint_detector_stats to authenticated;
revoke select on public.gate_keyword_performance from anon;
grant select on public.gate_keyword_performance to authenticated;
revoke select on public.kyle_steal_box from anon;
grant select on public.kyle_steal_box to authenticated;
revoke select on public.lm_dashboard_performance from anon;
grant select on public.lm_dashboard_performance to authenticated;
revoke select on public.lm_performance from anon;
grant select on public.lm_performance to authenticated;
revoke select on public.lm_today_activity from anon;
grant select on public.lm_today_activity to authenticated;
revoke select on public.lm_vertical_density from anon;
grant select on public.lm_vertical_density to authenticated;
revoke select on public.nurture_performance from anon;
grant select on public.nurture_performance to authenticated;
revoke select on public.outreach_dm_variant_clicks from anon;
grant select on public.outreach_dm_variant_clicks to authenticated;
revoke select on public.outreach_note_variant_readout from anon;
grant select on public.outreach_note_variant_readout to authenticated;
revoke select on public.outreach_seniority_share_30d from anon;
grant select on public.outreach_seniority_share_30d to authenticated;
revoke select on public.own_posts_scored from anon;
grant select on public.own_posts_scored to authenticated;
revoke select on public.pageviews_daily from anon;
grant select on public.pageviews_daily to authenticated;
revoke select on public.pageviews_device_split from anon;
grant select on public.pageviews_device_split to authenticated;
revoke select on public.pageviews_top_paths from anon;
grant select on public.pageviews_top_paths to authenticated;
revoke select on public.pageviews_top_referrers from anon;
grant select on public.pageviews_top_referrers to authenticated;
revoke select on public.pageviews_top_utm from anon;
grant select on public.pageviews_top_utm to authenticated;
revoke select on public.scan_open_stats from anon;
grant select on public.scan_open_stats to authenticated;
revoke select on public.scheduled_checks_due_for_notify from anon;
grant select on public.scheduled_checks_due_for_notify to authenticated;
revoke select on public.scheduled_checks_status from anon;
grant select on public.scheduled_checks_status to authenticated;
revoke select on public.scheduled_ops_status from anon;
grant select on public.scheduled_ops_status to authenticated;
revoke select on public.v_claude_memory_embedding_status from anon;
grant select on public.v_claude_memory_embedding_status to authenticated;
revoke select on public.v_claude_memory_link_counts from anon;
grant select on public.v_claude_memory_link_counts to authenticated;
revoke select on public.v_client_proposals from anon;
grant select on public.v_client_proposals to authenticated;
revoke select on public.v_n8nclaw_tool_usage_14d from anon;
grant select on public.v_n8nclaw_tool_usage_14d to authenticated;
revoke select on public.v_n8nclaw_tool_usage_7d from anon;
grant select on public.v_n8nclaw_tool_usage_7d to authenticated;
-- RPC hardening (overload-safe via pg_proc loop):
do $$ declare r record; begin
  for r in select p.oid::regprocedure sig, p.proname from pg_proc p join pg_namespace n on n.oid=p.pronamespace
    where n.nspname='public' and p.proname = any(array['dashboard_action','dashboard_create_task','delete_scheduled_post','n8nclaw_dashboard_send','newsletter_issue_upsert','newsletter_issue_approve','newsletter_issue_schedule','newsletter_issue_cancel','newsletter_issue_send_now','newsletter_issue_delete','newsletter_issue_create_from_draft','issue_fractional_session','health_add_inventory','health_add_medication','health_delete_inventory','health_delete_medication','health_log_medication','health_log_training','health_log_weight','health_update_training','recording_archive','recording_create_share','recording_extend_expiry','recording_manual_trim','recording_request_ai_trim','recording_stats','recording_storage_summary','recording_cleanup_expired','recording_expire_overdue','recording_expiring_soon','find_call_recording_for_session','append_agent_log','add_slack_channel','remove_slack_channel','toggle_slack_channel','mute_category','unmute_category','get_pending_actions','mark_pending_seen','get_recent_outreach_clicks','get_contact_360','get_contact_stage_counts','resolve_contacts','merge_contacts','aios_capabilities_overview','claude_usage_by_project','claude_usage_daily_totals','claude_usage_recent_sessions','content_post_heatmap','outreach_send_heatmap','outreach_pipeline_stats','outreach_advance_stage','outreach_sender_health','upwork_pipeline_stats','get_agency_dm_variant_stats','operator_client_actions','operator_client_drafts','operator_clients_overview','operator_set_board_visible','fire_editorial_webhook','dump_schema','acquire_generation_lock','release_generation_lock','claim_generation_job','requeue_stuck_generation_jobs','increment_error_count','bump_hot_domain_prospects','embed_audience_audit','auto_embed_pending_memory','backfill_own_posts_hook_type','fn_icp_drift_sweep','fn_auto_wire_lm_social_id','run_telemetry_sync','sync_kyle_raw_to_transcripts','record_post_fingerprint','gen_blueprint_share_token','gen_fractional_session_token','bump_edge_rate']) loop
    execute format('revoke execute on function %s from anon, public', r.sig);
    if r.proname <> all(array['acquire_generation_lock','auto_embed_pending_memory','backfill_own_posts_hook_type','bump_edge_rate','bump_hot_domain_prospects','claim_generation_job','dump_schema','embed_audience_audit','fire_editorial_webhook','fn_auto_wire_lm_social_id','fn_icp_drift_sweep','gen_blueprint_share_token','gen_fractional_session_token','increment_error_count','record_post_fingerprint','release_generation_lock','requeue_stuck_generation_jobs','run_telemetry_sync','sync_kyle_raw_to_transcripts']) then
      execute format('grant execute on function %s to authenticated', r.sig);
    end if;
  end loop; end $$;
